#!/bin/bash
# Copyright (c) 2021 Samuel T. Denton, III

usage="Pretty print various types of files

Usage: $0 [-t <TYPE>] <FILENAME>

TYPE is the file type, if it cannot be discerned from the file name.
Use - for standard input.'

while getopts "t:" arg
do
        case "${arg}" in
        t)
                opt_t=${OPTARG}
                ;;
        \?)
                echo "Error: Unknown option -${OPTARG}" >&2
                echo "$usage" >&2
                exit 1
                ;;
        esac
done
shift $((OPTIND-1))

: ${1?'Missing input file! (use "-" for stdin)'}

if [[ $opt_t = json || $1 == *.json ]]
then
        python -m json.tool $1
elif [[ $opt_t = xml || $1 == *.xml ]]
then
        xmllint --format $1
else
        echo 'Error: Unrecognized file type' >&2
        echo "$usage" >&2
fi
